### ISSUE TITLE
[BUG] Dkg returns invalid JSON

### ISSUE THREAD

**Issue by huantt** [getmeemaw/meemaw#8]
```go
func Dkg(this js.Value, args []js.Value) (any, error) {
	host := args[0].String()
	authData := args[1].String()

	dkgResult, metadata, err := client.Dkg(host, authData)
	if err != nil {
		log.Println("error while dkg:", err)
		return nil, err
	}

	dkgResultJSON, err := json.Marshal(dkgResult)
	if err != nil {
		log.Println("error while marshaling dkgresult json:", err)
		return nil, err
	}

	return metadata + "&&" + string(dkgResultJSON), err
}
```

I don't understand why you join the dkResultJSON with metadata; it's invalid JSON.

**Comment by huantt** [comment]
I leads to an error in [example-js](https://github.com/getmeemaw/example-js)

**Comment by marceaul** [comment]
Hey @huantt ,

Thanks for posting the issue!

Actually, the problem was in [example-js](https://github.com/getmeemaw/example-js), it was not updated to use the latest version of the SDK.
It should work now.

However, you’re right that it’s not the cleanest approach at all, it would make more sense to have it inside the JSON.
I will change it then close the issue.

Cheers

**Comment by marceaul** [comment]
Updated [here](https://github.com/getmeemaw/meemaw/commit/e6d285a42f5e3969a2e42a5da14d2a1a7c69e1a2), closing the issue.
